//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int Product { get; set; }
        public int Warehouse { get; set; }
        public string EntryDate { get; set; }
        public string ExitDate { get; set; }
    
        public virtual Product Product1 { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
